
const USERNAME_MIN_LENGTH = 6;
const USERNAME_MAX_LENGTH = 32;

const SIGNIN_AGE_MS = 7 * 24 * 60 * 60 * 1000;
const CHECK_AGE_MS = 5 * 60 * 1000;

export {
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH,
  SIGNIN_AGE_MS,
  CHECK_AGE_MS,
}